#pragma once
#include "Sprite.h"

typedef struct Ennemi {
	Sprite self;

	i32 HP;
} Ennemi;

typedef enum TypeEnnemi {
    TYPEENNEMI_OCTAHEDRON,
    TYPEENNEMI_DIAMANT,
    TYPEENNEMI_TOURNANT,
    TYPEENNEMI_ENERGIE,
    TYPEENNEMI_CROISSANT,
    TYPEENNEMI_DUPLIQUEUR,
    TYPEENNEMI_PATRA,
    TYPEENNEMI_OCTAHEDRON_DUR,
    TYPEENNEMI_DIAMANT_DUR,
    TYPEENNEMI_TOURNANT_DUR,
    TYPEENNEMI_ENERGIE_DUR,
    TYPEENNEMI_CROISSANT_DUR,
    TYPEENNEMI_DUPLIQUEUR_DUR,
    TYPEENNEMI_PATRA_DUR,
    TYPEENNEMI_BOSS,
    TYPEENNEMI_PATRA_MINION,
    TYPEENNEMI_PATRA_MINION_DUR
} TypeEnnemi;

typedef enum StatusEnnemi {
    STATUSENNEMI_VIDE = 0,
    STATUSENNEMI_INITIALIZATION,
    STATUSENNEMI_NORMAL,
    STATUSENNEMI_MORT,

    STATUSENNEMI_DUPLIQUEUR_0_RESTANT = 60,
    STATUSENNEMI_DUPLIQUEUR_1_RESTANT,
    STATUSENNEMI_DUPLIQUEUR_2_RESTANT,

    STATUSENNEMI_PATRA_0_RESTANT = 70,
    STATUSENNEMI_PATRA_1_RESTANT,
    STATUSENNEMI_PATRA_2_RESTANT,
    STATUSENNEMI_PATRA_3_RESTANT,
    STATUSENNEMI_PATRA_4_RESTANT,
    STATUSENNEMI_PATRA_5_RESTANT,
    STATUSENNEMI_PATRA_6_RESTANT,
    STATUSENNEMI_PATRA_7_RESTANT,
    STATUSENNEMI_PATRA_8_RESTANT,

    STATUSENNEMI_BOSS_INIT = 150,
    STATUSENNEMI_BOSS_INIT_2,
    STATUSENNEMI_BOSS_INIT_3,
    STATUSENNEMI_BOSS_NORMAL,
    STATUSENNEMI_BOSS_MORT,
    STATUSENNEMI_BOSS_MORT_2,
    STATUSENNEMI_BOSS_MORT_3,
} StatusEnnemi;

const int NB_TYPES_ENNEMIS = 17;
const int BOSS_MAX_HP = 150;
const int DISTANCE_DE_BORD_EVITER_INIT = 200;
const float VITESSE_MOYENNE_ENNEMI = 0.4f;
const float VITESSE_MOYENNE_Z_ENNEMI = 2.5f;
const float VITESSE_MOYENNE_TIR_ENNEMI = 0.2f;
const float ENNEMI_FRICTION = 0.8f;