#include "Niveaux.h"

extern int JouerEffet(Jeu* jeu, EffetAudio effet_a_jouer);
extern void DisplayText(Jeu* jeu, char* text, Vector2 position, float size, int color, int alpha, int scroll);

//const TypeEnnemi liste_nv_x[0] = { 0 }; // niveau 0
const TypeEnnemi liste_nv_1[] = { TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON }; // niveau 1
const TypeEnnemi liste_nv_2[] = { TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_OCTAHEDRON }; // niveau 2
const TypeEnnemi liste_nv_3[] = { TYPEENNEMI_TOURNANT, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_TOURNANT }; // niveau 3
const TypeEnnemi liste_nv_4[] = { TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_DIAMANT }; // niveau 4
const TypeEnnemi liste_nv_5[] = { TYPEENNEMI_TOURNANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_ENERGIE, TYPEENNEMI_ENERGIE, TYPEENNEMI_TOURNANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_ENERGIE, TYPEENNEMI_TOURNANT }; // niveau 5
const TypeEnnemi liste_nv_6[] = { TYPEENNEMI_ENERGIE, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_ENERGIE, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_TOURNANT, TYPEENNEMI_DIAMANT, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_OCTAHEDRON_DUR }; // niveau 6
const TypeEnnemi liste_nv_7[] = { TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_CROISSANT, TYPEENNEMI_CROISSANT, TYPEENNEMI_ENERGIE, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_CROISSANT }; // niveau 7
const TypeEnnemi liste_nv_8[] = { TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_DUPLIQUEUR, TYPEENNEMI_CROISSANT, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_DUPLIQUEUR, TYPEENNEMI_CROISSANT, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DUPLIQUEUR }; // niveau 8
const TypeEnnemi liste_nv_9[] = { TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_DUPLIQUEUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_PATRA, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_PATRA, TYPEENNEMI_DIAMANT_DUR }; // niveau 9
const TypeEnnemi liste_nv_10[] = { TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_PATRA, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_DIAMANT_DUR }; // niveau 10
const TypeEnnemi liste_nv_11[] = { TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_PATRA, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_OCTAHEDRON_DUR }; // niveau 11
const TypeEnnemi liste_nv_12[] = { TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_CROISSANT_DUR }; // niveau 12
const TypeEnnemi liste_nv_13[] = { TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DIAMANT_DUR }; // niveau 13
const TypeEnnemi liste_nv_14[] = { TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_TOURNANT_DUR }; // niveau 14
const TypeEnnemi liste_nv_15[] = { TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_TOURNANT_DUR }; // niveau 15
const TypeEnnemi liste_nv_16[] = { TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR }; // niveau 16
const TypeEnnemi liste_nv_17[] = { TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_CROISSANT_DUR }; // niveau 17
const TypeEnnemi liste_nv_18[] = { TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_PATRA_DUR }; // niveau 18
const TypeEnnemi liste_nv_19[] = { TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_PATRA_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_PATRA_DUR }; // niveau 19
const TypeEnnemi liste_nv_20[] = { TYPEENNEMI_BOSS }; // niveau 20

const TypeEnnemi* liste_niveaux[21] = {
	NULL, liste_nv_1, liste_nv_2, liste_nv_3, liste_nv_4, liste_nv_5, liste_nv_6, liste_nv_7, liste_nv_8, liste_nv_9, liste_nv_10, liste_nv_11, 
	liste_nv_12, liste_nv_13, liste_nv_14, liste_nv_15, liste_nv_16, liste_nv_17, liste_nv_18, liste_nv_19, liste_nv_20
};
const i32 liste_niveaux_longueures[21] = {
	0, 5, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 10, 1
};

const TypeEnnemi ennemis_valide_arcade[] = {
		TYPEENNEMI_OCTAHEDRON, TYPEENNEMI_DIAMANT, TYPEENNEMI_TOURNANT, TYPEENNEMI_ENERGIE, TYPEENNEMI_CROISSANT, TYPEENNEMI_DUPLIQUEUR, TYPEENNEMI_PATRA,
	TYPEENNEMI_OCTAHEDRON_DUR, TYPEENNEMI_DIAMANT_DUR, TYPEENNEMI_TOURNANT_DUR, TYPEENNEMI_ENERGIE_DUR, TYPEENNEMI_CROISSANT_DUR, TYPEENNEMI_DUPLIQUEUR_DUR, TYPEENNEMI_PATRA_DUR
};

i32 GenererListeArcade(Jeu* jeu) {

	const i32 VARIABILITE_ENNEMI_CHOISI = 2;
	const float RAPIDITE_DE_DIFFICULTE = 8.0f;

	if (jeu->niveau < 0) {

		return 0;
	}

	i32 longueure_liste_arcade = (i32)SDL_sqrtf(jeu->niveau * 10) + 2;

	if (longueure_liste_arcade < 0) {

		return 0;
	}

	if (jeu->liste_ennemis_arcade) {

		SDL_free(jeu->liste_ennemis_arcade);
	}

	jeu->liste_ennemis_arcade = SDL_malloc(sizeof(TypeEnnemi) * longueure_liste_arcade);

	i32 next_entry;
	i32 formule = (i32)(ARRAY_LEN(ennemis_valide_arcade) * jeu->niveau / (jeu->niveau + RAPIDITE_DE_DIFFICULTE));

	for (i32 i = 0; i < longueure_liste_arcade; i++) {

		next_entry = formule + RNG(-VARIABILITE_ENNEMI_CHOISI, VARIABILITE_ENNEMI_CHOISI + 1);

		if (next_entry < 0)
			next_entry = 0;
		else if (next_entry > longueure_liste_arcade)
			next_entry = longueure_liste_arcade;

		jeu->liste_ennemis_arcade[i] = next_entry;
	}

	return longueure_liste_arcade;
}

void ChangerNiveau(Jeu* jeu) {

	const i32 TEMPS_AVANT_TEXTE = (i32)(3.33f * G_FPS);
	const i32 TEMPS_TEXTE_SUR_ECRAN = (i32)(2.0f * G_FPS) + TEMPS_AVANT_TEXTE;
	const i32 TEMPS_APRES_TEXTE_PARTI = (i32)(0.5f + G_FPS) + TEMPS_TEXTE_SUR_ECRAN;

	if (jeu->gamemode == GAMEMODE_ARCADE && jeu->timer_changement_niveau < TEMPS_AVANT_TEXTE) {

		jeu->timer_changement_niveau = TEMPS_AVANT_TEXTE;
	}

	if (jeu->timer_changement_niveau == TEMPS_AVANT_TEXTE) {

		JouerEffet(jeu, EFFET_NIVEAU);
	}

	if (jeu->timer_changement_niveau > TEMPS_AVANT_TEXTE && jeu->timer_changement_niveau < TEMPS_APRES_TEXTE_PARTI) {

		char num[10];
		char txt[20] = "niveau ";
		SDL_itoa(jeu->niveau + 1, num, 10);
		SDL_strlcat(txt, num, 20);

		DisplayText(jeu, txt, (Vector2) { CENTRE, CENTRE }, 5, BLANC, OPAQUE, NO_SCROLL);
	}

	if (jeu->timer_changement_niveau >= TEMPS_APRES_TEXTE_PARTI) {

		jeu->niveau++;
		jeu->timer_changement_niveau = 0;

		if (jeu->gamemode == GAMEMODE_AVENTURE) {

			jeu->ennemis_restant = liste_niveaux_longueures[jeu->niveau];
		}
		else {

			jeu->ennemis_restant = GenererListeArcade(jeu);
			jeu->liste_ennemis_arcade_len = jeu->ennemis_restant;
		}

		jeu->ennemis_tues = 0;
	}

	jeu->timer_changement_niveau++;
}